### ISSUE TITLE
Kekulized QM9

### ISSUE THREAD

**Issue by nshervt** [chainer/chainer-chemistry#414]
I was wondering if the qm9 dataset can be loaded with the molecules Kekulized or should I simply  turn smiles to mol and kekulize it and extract data from that kekulized smiles? Thanks!

**Comment by corochann** [comment]
Each `Preprocessor` have `kekulize` option.
 - https://github.com/chainer/chainer-chemistry/blob/56e83dedb5de9dc9eb08ebf292be9ba76a4883ba/chainer_chemistry/dataset/preprocessors/nfp_preprocessor.py#L28

So when you call `get_qm9` method, you can pass preprocessor which is instantiated with `kekulize=True`
 - https://github.com/chainer/chainer-chemistry/blob/master/examples/qm9/train_qm9.py#L107-L113

**Comment by nshervt** [comment]
Thanks!
