### ISSUE TITLE
Relgat example not given

### ISSUE THREAD

**Issue by Ujwal2910** [chainer/chainer-chemistry#416]
Could you please add an example of the implementation of Relgat network?

**Comment by corochann** [comment]
I think RelGAT example exists.

https://github.com/chainer/chainer-chemistry/blob/master/examples/qm9/train_qm9.py#L30

Can you try running below command to train RelGAT architecture?

`python train_qm9.py --method relgat`

**Comment by corochann** [comment]
Can you train RelGAT? Let me close the issue.
